/* font_family monospace */
/* font_family Hack */
font_family MesloLGSDZ Nerd Font Mono
bold_font MesloLGSDZ Nerd Font Mono
italic_font Cascadia Mono NF
bold_italic_font Cascadia Mono NF

# font_features CascadiaMonoNF +ss01
# font_features CascadiaMonoNF-Italic +ss01

font_size 18.0

macos_option_as_alt both

/* modify_font underline_position 0px */
/* modify_font underline_thickness 100% */
modify_font underline_position 18
/* modify_font underline_thickness 250% */
# modify_font strikethrough_position 2px

/* symbol_map U+EB8A Hack */
/* background_image ~/development/T/wallpapers/gradients/bkg3_bkg5.png */
/* background_image_layout scaled */

background #1e1e2e
/* background_opacity 0.5 */

cursor_trail 3
